name: YAML to JSON
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
    verify-json-validation:
        runs-on: ubuntu-latest
        steps:
            - name: Set foobar to cool
              uses: mikefarah/yq@master
              with:
                cmd: yq test/test-yaml.yml --prettyPrint -o=json > test-json.json
            - uses: actions/checkout@v1
            - name: Validate JSON
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                INPUT_SCHEMA: /home/runner/work/actions-test/actions-test/schema.json
                INPUT_JSONS: test-json.json
 