name: YAML to JSON
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
    verify-json-validation:
        runs-on: ubuntu-latest
        steps:
            - name: Install yq
              run: snap install yq --channel=v3/stable
            - name: Create JSON file
              run: yq r --prettyPrint -j test/test-yaml.yml > test-json.json
              working-directory: test
            - uses: actions/checkout@v1
            - name: Validate JSON
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                INPUT_SCHEMA: schema.json
                INPUT_JSONS: test/test-json.json
 